# Generated by Django 2.1 on 2019-04-11 09:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_auto_20190411_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
