# Generated by Django 2.1 on 2019-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_producttranslation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
